# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Developer experiences
author: Maarten Gregoire
email: maarten.gregoire@cegeka.com
description: >- # this means to ignore newlines until "baseurl:"
  In this blog I write articles about my experiences as a developer. The focus is Java and Typescript.
baseurl: ""
url: ""
twitter_username: 
github_username:  maarten-gregoire
repo: https://github.com/maarten-gregoire

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/Thomasvanausloos
    icon: /i/icons.svg#github
    outbound: true # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto # these keys enable email obfuscation.
    handle: hello # you know, to protect you from bots. (handle and domain
    domain: github.com # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag: { output: true }

defaults:
  - scope: { type: posts }
    values: { layout: post }
  - scope: { type: tag }
    values: { layout: listing }
  - scope: { type: category }
    values: { layout: listing }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
